# Generated by Django 3.2.7 on 2021-09-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_auto_20210924_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='include_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='include_retweets',
            field=models.BooleanField(default=False),
        ),
    ]
