# Generated by Django 3.2.7 on 2021-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_auto_20210928_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
