# Generated by Django 4.1.8 on 2023-04-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_followers_friends_twittermonitoring_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittermonitoring',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='monitorings_followers', to='monitoring.followers'),
        ),
        migrations.AlterField(
            model_name='twittermonitoring',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='monitorings_friends', to='monitoring.friends'),
        ),
    ]
