# Generated by Django 4.1.8 on 2023-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_twittermonitoring_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittermonitoring',
            name='followers',
        ),
        migrations.AlterField(
            model_name='twittermonitoring',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='monitorings_friends', to='monitoring.friends'),
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
