# Generated by Django 4.1.8 on 2023-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_remove_twittermonitoring_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittermonitoring',
            name='telegram_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
