# Generated by Django 4.1.8 on 2023-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_twittermonitoring_telegram_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittermonitoring',
            name='telegram_channel',
            field=models.CharField(blank=True, help_text='It is an integer value field that represents the id of the telegram channel.\nIn order to obtain this id, you should create a public channel (can be changed later), copy the joining link and paste it to this bot: https://t.me/username_to_id_bot. Then just copy an id from the output and paste it here', max_length=255, null=True),
        ),
    ]
