# Generated by Django 4.1.8 on 2023-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_twittermonitoring_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='twitter_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
